apiVersion: v1
kind: PersistentVolume

metadata:
  name: mysql-pv
  namespace: mysql-server

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /var/lib/mysql
