apiVersion: v1
kind: Service

metadata:
  name: mysql-service
  namespace: mysql-server

spec:
  selector:
    app: mysql-service
  type: LoadBalancer
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306